# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasarimlar/frmAnasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmAnaSayfa(object):
    def setupUi(self, frmAnaSayfa):
        frmAnaSayfa.setObjectName("frmAnaSayfa")
        frmAnaSayfa.setWindowModality(QtCore.Qt.NonModal)
        frmAnaSayfa.resize(2140, 1080)
        frmAnaSayfa.setMaximumSize(QtCore.QSize(16777215, 16777215))
        frmAnaSayfa.setStyleSheet("#frmAnaSayfa{\n"
"    border-image: url(:/butonlar/15.jpg);\n"
"    border-image: url(:/arkaplan/3607424.jpg);\n"
"}")
        self.label = QtWidgets.QLabel(frmAnaSayfa)
        self.label.setGeometry(QtCore.QRect(1610, 15, 61, 51))
        self.label.setStyleSheet("border-image: url(:/iconlar/user.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(frmAnaSayfa)
        self.label_2.setGeometry(QtCore.QRect(1270, 15, 61, 51))
        self.label_2.setStyleSheet("border-image: url(:/iconlar/server.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(frmAnaSayfa)
        self.label_3.setGeometry(QtCore.QRect(1440, 15, 61, 51))
        self.label_3.setStyleSheet("border-image: url(:/iconlar/signal.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(frmAnaSayfa)
        self.label_4.setGeometry(QtCore.QRect(1340, 30, 71, 21))
        self.label_4.setStyleSheet("color:white;\n"
"font: 87 10pt \"Arial Black\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(frmAnaSayfa)
        self.label_5.setGeometry(QtCore.QRect(1510, 30, 81, 21))
        self.label_5.setStyleSheet("color:white;\n"
"font: 87 10pt \"Arial Black\";\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(frmAnaSayfa)
        self.label_6.setGeometry(QtCore.QRect(1680, 30, 81, 21))
        self.label_6.setStyleSheet("color:white;\n"
"font: 87 10pt \"Arial Black\";\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(frmAnaSayfa)
        self.label_7.setGeometry(QtCore.QRect(1340, 50, 71, 21))
        self.label_7.setStyleSheet("color:#20dad8;\n"
"font: 87 10pt \"Arial Black\";\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(frmAnaSayfa)
        self.label_8.setGeometry(QtCore.QRect(1510, 50, 81, 21))
        self.label_8.setStyleSheet("color:#20dad8;\n"
"font: 87 10pt \"Arial Black\";\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(frmAnaSayfa)
        self.label_9.setGeometry(QtCore.QRect(1680, 50, 81, 21))
        self.label_9.setStyleSheet("color:#20dad8;\n"
"font: 87 10pt \"Arial Black\";\n"
"")
        self.label_9.setObjectName("label_9")
        self.pushButton_2 = QtWidgets.QPushButton(frmAnaSayfa)
        self.pushButton_2.setGeometry(QtCore.QRect(1750, 20, 61, 51))
        self.pushButton_2.setStyleSheet("border-image: url(:/iconlar/gear.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_11 = QtWidgets.QLabel(frmAnaSayfa)
        self.label_11.setGeometry(QtCore.QRect(1820, 35, 81, 21))
        self.label_11.setStyleSheet("color:white;\n"
"font: 87 10pt \"Arial Black\";\n"
"")
        self.label_11.setObjectName("label_11")
        self.listwdgSepet = QtWidgets.QListWidget(frmAnaSayfa)
        self.listwdgSepet.setGeometry(QtCore.QRect(1595, 90, 311, 861))
        self.listwdgSepet.setStyleSheet("#listwdgSepet{\n"
"    font: 87 8pt \"Arial Black\";\n"
"    background-color: #002a41;\n"
"    border: 3px solid #002a41;  /* Çerçeve rengi ve kalınlığı */\n"
"    border-radius: 10px;        /* Köşe yuvarlama */\n"
"    padding: 10px;              /* İç boşluk */\n"
"    padding-top: 60px;\n"
"    padding-bottom: 270px\n"
"}\n"
"QListWidget::item {\n"
"    color: #ffffff; /* Yazı rengi */\n"
"    padding: 3px; /* İç boşluk */\n"
"    min-height: 10px; /* Öğenin minimum yüksekliği */\n"
"}")
        self.listwdgSepet.setObjectName("listwdgSepet")
        self.pushButton_4 = QtWidgets.QPushButton(frmAnaSayfa)
        self.pushButton_4.setGeometry(QtCore.QRect(1640, 100, 61, 51))
        self.pushButton_4.setStyleSheet("\n"
"border-image: url(:/iconlar/Graphicloads-100-Flat-Currency.256.png);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_10 = QtWidgets.QLabel(frmAnaSayfa)
        self.label_10.setGeometry(QtCore.QRect(1730, 100, 71, 51))
        self.label_10.setStyleSheet("color:white;\n"
"background-color: #be5068;\n"
"font: 87 12pt \"Arial Black\";\n"
"border-radius: 10px;\n"
"text-align: center;          \n"
"vertical-align: middle;      \n"
"padding: 0;\n"
"")
        self.label_10.setScaledContents(False)
        self.label_10.setOpenExternalLinks(False)
        self.label_10.setObjectName("label_10")
        self.lineIndirim = QtWidgets.QLineEdit(frmAnaSayfa)
        self.lineIndirim.setGeometry(QtCore.QRect(1610, 740, 91, 31))
        self.lineIndirim.setStyleSheet("color:black;\n"
"background-color: white;\n"
"font: 87 12pt \"Arial Black\";\n"
"border-radius: 10px;\n"
"text-align: center;          \n"
"vertical-align: middle;      \n"
"padding: 0;\n"
"")
        self.lineIndirim.setText("")
        self.lineIndirim.setObjectName("lineIndirim")
        self.btnSepetGuncelle = QtWidgets.QPushButton(frmAnaSayfa)
        self.btnSepetGuncelle.setGeometry(QtCore.QRect(1730, 710, 121, 31))
        self.btnSepetGuncelle.setStyleSheet("color:white;\n"
"background-color: #be5068;\n"
"font: 87 8pt \"Arial Black\";\n"
"border-radius: 10px;\n"
"text-align: center;          \n"
"vertical-align: middle;      \n"
"padding: 0;\n"
"")
        self.btnSepetGuncelle.setObjectName("btnSepetGuncelle")
        self.btnOdeme = QtWidgets.QPushButton(frmAnaSayfa)
        self.btnOdeme.setGeometry(QtCore.QRect(1700, 880, 121, 41))
        self.btnOdeme.setStyleSheet("#btnOdeme{\n"
"border-image: url(:/butonlar/15.jpg);\n"
"}\n"
"#btnOdeme:hover{\n"
"border-image: url(:/butonlar/11.jpg);}\n"
"\n"
"")
        self.btnOdeme.setText("")
        self.btnOdeme.setObjectName("btnOdeme")
        self.label_14 = QtWidgets.QLabel(frmAnaSayfa)
        self.label_14.setGeometry(QtCore.QRect(1610, 840, 131, 21))
        self.label_14.setStyleSheet("color:white;\n"
"font: 87 10pt \"Arial Black\";\n"
"")
        self.label_14.setObjectName("label_14")
        self.lblToplamFiat = QtWidgets.QLabel(frmAnaSayfa)
        self.lblToplamFiat.setGeometry(QtCore.QRect(1830, 840, 81, 21))
        self.lblToplamFiat.setStyleSheet("color:white;\n"
"font: 87 10pt \"Arial Black\";\n"
"")
        self.lblToplamFiat.setObjectName("lblToplamFiat")
        self.label_15 = QtWidgets.QLabel(frmAnaSayfa)
        self.label_15.setGeometry(QtCore.QRect(1610, 800, 131, 21))
        self.label_15.setStyleSheet("color:white;\n"
"font: 87 10pt \"Arial Black\";\n"
"")
        self.label_15.setObjectName("label_15")
        self.lblKdv = QtWidgets.QLabel(frmAnaSayfa)
        self.lblKdv.setGeometry(QtCore.QRect(1830, 800, 81, 21))
        self.lblKdv.setStyleSheet("color:white;\n"
"font: 87 10pt \"Arial Black\";\n"
"")
        self.lblKdv.setObjectName("lblKdv")
        self.btnIndirimKaldir = QtWidgets.QPushButton(frmAnaSayfa)
        self.btnIndirimKaldir.setGeometry(QtCore.QRect(1730, 750, 121, 31))
        self.btnIndirimKaldir.setStyleSheet("color:white;\n"
"background-color: #be5068;\n"
"font: 87 8pt \"Arial Black\";\n"
"border-radius: 10px;\n"
"text-align: center;          \n"
"vertical-align: middle;      \n"
"padding: 0;\n"
"")
        self.btnIndirimKaldir.setObjectName("btnIndirimKaldir")
        self.scrollUrunler = QtWidgets.QScrollArea(frmAnaSayfa)
        self.scrollUrunler.setGeometry(QtCore.QRect(20, 100, 1561, 881))
        self.scrollUrunler.setStyleSheet("background-color: transparent; /* Tamamen şeffaf arka plan */\n"
"\n"
"\n"
"")
        self.scrollUrunler.setWidgetResizable(True)
        self.scrollUrunler.setObjectName("scrollUrunler")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1538, 5022))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.urunlerFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.urunlerFrame.setMinimumSize(QtCore.QSize(0, 5000))
        self.urunlerFrame.setStyleSheet("#urunlerFrame{\n"
"selection-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.urunlerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.urunlerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.urunlerFrame.setObjectName("urunlerFrame")
        self.btnSepetekle4 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle4.setGeometry(QtCore.QRect(770, 220, 51, 41))
        self.btnSepetekle4.setStyleSheet("border-image: url(:/iconlar/Custom-Icon-Design-Flatastic-4-Shopping-cart-add.512.png);\n"
"border-rodius:15px;")
        self.btnSepetekle4.setText("")
        self.btnSepetekle4.setObjectName("btnSepetekle4")
        self.lbl1 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl1.setGeometry(QtCore.QRect(80, 10, 151, 131))
        self.lbl1.setStyleSheet("border-image: url(:/iconlar/silgi.jpg);\n"
"border-radius: 10px;")
        self.lbl1.setText("")
        self.lbl1.setObjectName("lbl1")
        self.lblFiat3 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat3.setGeometry(QtCore.QRect(540, 180, 101, 41))
        self.lblFiat3.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat3.setObjectName("lblFiat3")
        self.lblFiat2 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat2.setGeometry(QtCore.QRect(330, 180, 101, 41))
        self.lblFiat2.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat2.setObjectName("lblFiat2")
        self.lbl2 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl2.setGeometry(QtCore.QRect(290, 10, 151, 131))
        self.lbl2.setStyleSheet("border-image: url(:/iconlar/kalem.png);\n"
"border-radius: 10px;")
        self.lbl2.setText("")
        self.lbl2.setObjectName("lbl2")
        self.btnSepetekle1 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle1.setGeometry(QtCore.QRect(130, 220, 51, 41))
        self.btnSepetekle1.setStyleSheet("border-image: url(:/iconlar/Custom-Icon-Design-Flatastic-4-Shopping-cart-add.512.png);\n"
"border-rodius:15px;")
        self.btnSepetekle1.setText("")
        self.btnSepetekle1.setObjectName("btnSepetekle1")
        self.btnSepetekle3 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle3.setGeometry(QtCore.QRect(550, 220, 51, 41))
        self.btnSepetekle3.setStyleSheet("border-image: url(:/iconlar/Custom-Icon-Design-Flatastic-4-Shopping-cart-add.512.png);\n"
"border-rodius:15px;")
        self.btnSepetekle3.setText("")
        self.btnSepetekle3.setObjectName("btnSepetekle3")
        self.btnSepetekle2 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle2.setGeometry(QtCore.QRect(340, 220, 51, 41))
        self.btnSepetekle2.setStyleSheet("border-image: url(:/iconlar/Custom-Icon-Design-Flatastic-4-Shopping-cart-add.512.png);\n"
"border-rodius:15px;")
        self.btnSepetekle2.setText("")
        self.btnSepetekle2.setObjectName("btnSepetekle2")
        self.lbl4 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl4.setGeometry(QtCore.QRect(710, 10, 151, 131))
        self.lbl4.setStyleSheet("border-image: url(:/iconlar/kalemTiras.png);\n"
"border-radius: 10px;")
        self.lbl4.setText("")
        self.lbl4.setObjectName("lbl4")
        self.txtDefter = QtWidgets.QLabel(self.urunlerFrame)
        self.txtDefter.setGeometry(QtCore.QRect(520, 150, 111, 41))
        self.txtDefter.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txtDefter.setObjectName("txtDefter")
        self.lblFiat1 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat1.setGeometry(QtCore.QRect(120, 180, 101, 41))
        self.lblFiat1.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat1.setObjectName("lblFiat1")
        self.lblFiat4 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat4.setGeometry(QtCore.QRect(760, 180, 101, 41))
        self.lblFiat4.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat4.setObjectName("lblFiat4")
        self.txt4 = QtWidgets.QLabel(self.urunlerFrame)
        self.txt4.setGeometry(QtCore.QRect(690, 150, 211, 41))
        self.txt4.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txt4.setObjectName("txt4")
        self.txt1 = QtWidgets.QLabel(self.urunlerFrame)
        self.txt1.setGeometry(QtCore.QRect(110, 150, 91, 41))
        self.txt1.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txt1.setObjectName("txt1")
        self.lbl3 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl3.setGeometry(QtCore.QRect(500, 10, 151, 131))
        self.lbl3.setStyleSheet("border-image: url(:/iconlar/defter.png);\n"
"border-radius: 10px;")
        self.lbl3.setText("")
        self.lbl3.setObjectName("lbl3")
        self.txt2 = QtWidgets.QLabel(self.urunlerFrame)
        self.txt2.setGeometry(QtCore.QRect(310, 150, 111, 41))
        self.txt2.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txt2.setObjectName("txt2")
        self.lblFiat4_6 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat4_6.setGeometry(QtCore.QRect(320, 450, 101, 41))
        self.lblFiat4_6.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat4_6.setText("")
        self.lblFiat4_6.setObjectName("lblFiat4_6")
        self.btnSepetekle8 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle8.setGeometry(QtCore.QRect(140, 490, 51, 41))
        self.btnSepetekle8.setStyleSheet("border-image: url(:/iconlar/Custom-Icon-Design-Flatastic-4-Shopping-cart-add.512.png);\n"
"border-rodius:15px;")
        self.btnSepetekle8.setText("")
        self.btnSepetekle8.setObjectName("btnSepetekle8")
        self.lbl8 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl8.setGeometry(QtCore.QRect(80, 280, 151, 131))
        self.lbl8.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-radius: 10px;")
        self.lbl8.setText("")
        self.lbl8.setObjectName("lbl8")
        self.lblFiat4_7 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat4_7.setGeometry(QtCore.QRect(130, 450, 101, 41))
        self.lblFiat4_7.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat4_7.setText("")
        self.lblFiat4_7.setObjectName("lblFiat4_7")
        self.txt4_6 = QtWidgets.QLabel(self.urunlerFrame)
        self.txt4_6.setGeometry(QtCore.QRect(250, 420, 211, 41))
        self.txt4_6.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txt4_6.setText("")
        self.txt4_6.setObjectName("txt4_6")
        self.txt4_7 = QtWidgets.QLabel(self.urunlerFrame)
        self.txt4_7.setGeometry(QtCore.QRect(60, 420, 211, 41))
        self.txt4_7.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txt4_7.setText("")
        self.txt4_7.setObjectName("txt4_7")
        self.lbl4_7 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl4_7.setGeometry(QtCore.QRect(270, 280, 151, 131))
        self.lbl4_7.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-radius: 10px;")
        self.lbl4_7.setText("")
        self.lbl4_7.setObjectName("lbl4_7")
        self.btnSepetekle9 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle9.setGeometry(QtCore.QRect(330, 490, 51, 41))
        self.btnSepetekle9.setStyleSheet("border-image: url(:/iconlar/Custom-Icon-Design-Flatastic-4-Shopping-cart-add.512.png);\n"
"border-rodius:15px;")
        self.btnSepetekle9.setText("")
        self.btnSepetekle9.setObjectName("btnSepetekle9")
        self.txt4_8 = QtWidgets.QLabel(self.urunlerFrame)
        self.txt4_8.setGeometry(QtCore.QRect(670, 420, 211, 41))
        self.txt4_8.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txt4_8.setText("")
        self.txt4_8.setObjectName("txt4_8")
        self.lbl4_8 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl4_8.setGeometry(QtCore.QRect(500, 280, 151, 131))
        self.lbl4_8.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-radius: 10px;")
        self.lbl4_8.setText("")
        self.lbl4_8.setObjectName("lbl4_8")
        self.btnSepetekle11 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle11.setGeometry(QtCore.QRect(750, 490, 51, 41))
        self.btnSepetekle11.setStyleSheet("border-image: url(:/iconlar/Custom-Icon-Design-Flatastic-4-Shopping-cart-add.512.png);\n"
"border-rodius:15px;")
        self.btnSepetekle11.setText("")
        self.btnSepetekle11.setObjectName("btnSepetekle11")
        self.btnSepetekle10 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle10.setGeometry(QtCore.QRect(560, 490, 51, 41))
        self.btnSepetekle10.setStyleSheet("border-image: url(:/iconlar/Custom-Icon-Design-Flatastic-4-Shopping-cart-add.512.png);\n"
"border-rodius:15px;")
        self.btnSepetekle10.setText("")
        self.btnSepetekle10.setObjectName("btnSepetekle10")
        self.txt4_9 = QtWidgets.QLabel(self.urunlerFrame)
        self.txt4_9.setGeometry(QtCore.QRect(480, 420, 211, 41))
        self.txt4_9.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txt4_9.setText("")
        self.txt4_9.setObjectName("txt4_9")
        self.lbl4_9 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl4_9.setGeometry(QtCore.QRect(690, 280, 151, 131))
        self.lbl4_9.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-radius: 10px;")
        self.lbl4_9.setText("")
        self.lbl4_9.setObjectName("lbl4_9")
        self.lblFiat4_8 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat4_8.setGeometry(QtCore.QRect(740, 450, 101, 41))
        self.lblFiat4_8.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat4_8.setText("")
        self.lblFiat4_8.setObjectName("lblFiat4_8")
        self.lblFiat4_9 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat4_9.setGeometry(QtCore.QRect(550, 450, 101, 41))
        self.lblFiat4_9.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat4_9.setText("")
        self.lblFiat4_9.setObjectName("lblFiat4_9")
        self.txt4_10 = QtWidgets.QLabel(self.urunlerFrame)
        self.txt4_10.setGeometry(QtCore.QRect(480, 670, 211, 41))
        self.txt4_10.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txt4_10.setText("")
        self.txt4_10.setObjectName("txt4_10")
        self.lbl4_10 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl4_10.setGeometry(QtCore.QRect(690, 530, 151, 131))
        self.lbl4_10.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-radius: 10px;")
        self.lbl4_10.setText("")
        self.lbl4_10.setObjectName("lbl4_10")
        self.txt4_11 = QtWidgets.QLabel(self.urunlerFrame)
        self.txt4_11.setGeometry(QtCore.QRect(670, 670, 211, 41))
        self.txt4_11.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txt4_11.setText("")
        self.txt4_11.setObjectName("txt4_11")
        self.txt4_12 = QtWidgets.QLabel(self.urunlerFrame)
        self.txt4_12.setGeometry(QtCore.QRect(250, 670, 211, 41))
        self.txt4_12.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txt4_12.setText("")
        self.txt4_12.setObjectName("txt4_12")
        self.lbl4_11 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl4_11.setGeometry(QtCore.QRect(500, 530, 151, 131))
        self.lbl4_11.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-radius: 10px;")
        self.lbl4_11.setText("")
        self.lbl4_11.setObjectName("lbl4_11")
        self.lbl4_12 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl4_12.setGeometry(QtCore.QRect(80, 530, 151, 131))
        self.lbl4_12.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-radius: 10px;")
        self.lbl4_12.setText("")
        self.lbl4_12.setObjectName("lbl4_12")
        self.lblFiat4_10 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat4_10.setGeometry(QtCore.QRect(740, 700, 101, 41))
        self.lblFiat4_10.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat4_10.setText("")
        self.lblFiat4_10.setObjectName("lblFiat4_10")
        self.lblFiat4_11 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat4_11.setGeometry(QtCore.QRect(550, 700, 101, 41))
        self.lblFiat4_11.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat4_11.setText("")
        self.lblFiat4_11.setObjectName("lblFiat4_11")
        self.btnSepetekle4_10 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle4_10.setGeometry(QtCore.QRect(560, 740, 51, 41))
        self.btnSepetekle4_10.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-rodius:15px;")
        self.btnSepetekle4_10.setText("")
        self.btnSepetekle4_10.setObjectName("btnSepetekle4_10")
        self.btnSepetekle4_11 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle4_11.setGeometry(QtCore.QRect(330, 740, 51, 41))
        self.btnSepetekle4_11.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-rodius:15px;")
        self.btnSepetekle4_11.setText("")
        self.btnSepetekle4_11.setObjectName("btnSepetekle4_11")
        self.txt4_13 = QtWidgets.QLabel(self.urunlerFrame)
        self.txt4_13.setGeometry(QtCore.QRect(60, 670, 211, 41))
        self.txt4_13.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txt4_13.setText("")
        self.txt4_13.setObjectName("txt4_13")
        self.btnSepetekle4_12 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle4_12.setGeometry(QtCore.QRect(140, 740, 51, 41))
        self.btnSepetekle4_12.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-rodius:15px;")
        self.btnSepetekle4_12.setText("")
        self.btnSepetekle4_12.setObjectName("btnSepetekle4_12")
        self.btnSepetekle4_13 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle4_13.setGeometry(QtCore.QRect(750, 740, 51, 41))
        self.btnSepetekle4_13.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-rodius:15px;")
        self.btnSepetekle4_13.setText("")
        self.btnSepetekle4_13.setObjectName("btnSepetekle4_13")
        self.lbl4_13 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl4_13.setGeometry(QtCore.QRect(270, 530, 151, 131))
        self.lbl4_13.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-radius: 10px;")
        self.lbl4_13.setText("")
        self.lbl4_13.setObjectName("lbl4_13")
        self.lblFiat4_12 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat4_12.setGeometry(QtCore.QRect(320, 700, 101, 41))
        self.lblFiat4_12.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat4_12.setText("")
        self.lblFiat4_12.setObjectName("lblFiat4_12")
        self.lblFiat4_13 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat4_13.setGeometry(QtCore.QRect(130, 700, 101, 41))
        self.lblFiat4_13.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat4_13.setText("")
        self.lblFiat4_13.setObjectName("lblFiat4_13")
        self.btnSepetekle5 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle5.setGeometry(QtCore.QRect(980, 220, 51, 41))
        self.btnSepetekle5.setStyleSheet("border-image: url(:/iconlar/Custom-Icon-Design-Flatastic-4-Shopping-cart-add.512.png);\n"
"border-rodius:15px;")
        self.btnSepetekle5.setText("")
        self.btnSepetekle5.setObjectName("btnSepetekle5")
        self.lbl5 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl5.setGeometry(QtCore.QRect(920, 10, 151, 131))
        self.lbl5.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-radius: 10px;")
        self.lbl5.setText("")
        self.lbl5.setObjectName("lbl5")
        self.txt5 = QtWidgets.QLabel(self.urunlerFrame)
        self.txt5.setGeometry(QtCore.QRect(900, 150, 211, 41))
        self.txt5.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txt5.setText("")
        self.txt5.setObjectName("txt5")
        self.lblFiat5 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat5.setGeometry(QtCore.QRect(970, 180, 101, 41))
        self.lblFiat5.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat5.setText("")
        self.lblFiat5.setObjectName("lblFiat5")
        self.lblFiat6 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat6.setGeometry(QtCore.QRect(1170, 180, 101, 41))
        self.lblFiat6.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat6.setText("")
        self.lblFiat6.setObjectName("lblFiat6")
        self.btnSepetekle6 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle6.setGeometry(QtCore.QRect(1180, 220, 51, 41))
        self.btnSepetekle6.setStyleSheet("border-image: url(:/iconlar/Custom-Icon-Design-Flatastic-4-Shopping-cart-add.512.png);\n"
"border-rodius:15px;")
        self.btnSepetekle6.setText("")
        self.btnSepetekle6.setObjectName("btnSepetekle6")
        self.lbl6 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl6.setGeometry(QtCore.QRect(1120, 10, 151, 131))
        self.lbl6.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-radius: 10px;")
        self.lbl6.setText("")
        self.lbl6.setObjectName("lbl6")
        self.txt6 = QtWidgets.QLabel(self.urunlerFrame)
        self.txt6.setGeometry(QtCore.QRect(1100, 150, 211, 41))
        self.txt6.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txt6.setText("")
        self.txt6.setObjectName("txt6")
        self.btnSepetekle7 = QtWidgets.QPushButton(self.urunlerFrame)
        self.btnSepetekle7.setGeometry(QtCore.QRect(1390, 220, 51, 41))
        self.btnSepetekle7.setStyleSheet("border-image: url(:/iconlar/Custom-Icon-Design-Flatastic-4-Shopping-cart-add.512.png);\n"
"border-rodius:15px;")
        self.btnSepetekle7.setText("")
        self.btnSepetekle7.setObjectName("btnSepetekle7")
        self.lbl7 = QtWidgets.QLabel(self.urunlerFrame)
        self.lbl7.setGeometry(QtCore.QRect(1330, 10, 151, 131))
        self.lbl7.setStyleSheet("border-image: url(:/iconlar/);\n"
"border-radius: 10px;")
        self.lbl7.setText("")
        self.lbl7.setObjectName("lbl7")
        self.txt7 = QtWidgets.QLabel(self.urunlerFrame)
        self.txt7.setGeometry(QtCore.QRect(1310, 150, 211, 41))
        self.txt7.setStyleSheet("color:white;\n"
"font: 87 20pt \"Arial Black\";\n"
"")
        self.txt7.setText("")
        self.txt7.setObjectName("txt7")
        self.lblFiat7 = QtWidgets.QLabel(self.urunlerFrame)
        self.lblFiat7.setGeometry(QtCore.QRect(1380, 180, 101, 41))
        self.lblFiat7.setStyleSheet("color:white;\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.lblFiat7.setText("")
        self.lblFiat7.setObjectName("lblFiat7")
        self.verticalLayout.addWidget(self.urunlerFrame)
        self.scrollUrunler.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(frmAnaSayfa)
        QtCore.QMetaObject.connectSlotsByName(frmAnaSayfa)

    def retranslateUi(self, frmAnaSayfa):
        _translate = QtCore.QCoreApplication.translate
        frmAnaSayfa.setWindowTitle(_translate("frmAnaSayfa", "Form"))
        self.label_4.setText(_translate("frmAnaSayfa", "Server"))
        self.label_5.setText(_translate("frmAnaSayfa", "Internet"))
        self.label_6.setText(_translate("frmAnaSayfa", "User"))
        self.label_7.setText(_translate("frmAnaSayfa", "Bağlı"))
        self.label_8.setText(_translate("frmAnaSayfa", "Bağlı"))
        self.label_9.setText(_translate("frmAnaSayfa", "Bağlı"))
        self.label_11.setText(_translate("frmAnaSayfa", "Ayarlar"))
        self.label_10.setText(_translate("frmAnaSayfa", "Sepet"))
        self.lineIndirim.setPlaceholderText(_translate("frmAnaSayfa", "İndirim"))
        self.btnSepetGuncelle.setText(_translate("frmAnaSayfa", "indirim uygula"))
        self.label_14.setText(_translate("frmAnaSayfa", "Toplam Fiyat:"))
        self.lblToplamFiat.setText(_translate("frmAnaSayfa", "0 TL"))
        self.label_15.setText(_translate("frmAnaSayfa", "Kdv:"))
        self.lblKdv.setText(_translate("frmAnaSayfa", "0 TL"))
        self.btnIndirimKaldir.setText(_translate("frmAnaSayfa", "indirimi kaldır"))
        self.lblFiat3.setText(_translate("frmAnaSayfa", "65 TL"))
        self.lblFiat2.setText(_translate("frmAnaSayfa", "15 TL"))
        self.txtDefter.setText(_translate("frmAnaSayfa", "defter"))
        self.lblFiat1.setText(_translate("frmAnaSayfa", "20 TL"))
        self.lblFiat4.setText(_translate("frmAnaSayfa", "10 TL"))
        self.txt4.setText(_translate("frmAnaSayfa", "kalemtraş"))
        self.txt1.setText(_translate("frmAnaSayfa", "silgi"))
        self.txt2.setText(_translate("frmAnaSayfa", "kalem"))
import arkaplanlar_rc
import butonlar_rc
import iconlar_rc
import ürünler_rc
